apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-namespace
spec:
  selector:
    app: api-pod
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8000
  type: ClusterIP