// Github repo
def app_config_repo = "https://github.com/VuHuy-cse-9/prompt-gruardrail-serving-model"
def app_config_branch = 'argocd'

// Helm
def helm_value_file = 'helm/prompt-guardrail/values.yaml'

// Docker image version 
def version = "v1.${BUILD_NUMBER}"

docker_build_command = "api/."

pipeline {
    agent any

    options{
        // Max number of build logs to keep and days to keep
        buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
        // Enable timestamp at each job in the pipeline
        timestamps()
    }

    environment{
        // Docker registry
        docker_registry = "https://index.docker.io/v1/"
        docker_image_name = 'vnminhhuy2001/prompt-guardrail-service'
        docker_credentials_id = '5ed17986-fa3b-4a9d-978d-73601852a852'     

    }

    stages {
        // stage('Test') {
        //     agent {
        //         docker {
        //             image 'python:3.12' 
        //         }
        //     }
        //     steps {
        //         script {                    
        //             // Install dependencies into the virtual environment
        //             echo 'Testing model correctness..'
        //             sh 'pip install -r api/requirements.txt && pytest'
        //         }
        //     }
        // }
        stage('Build') {
            steps {
                script {
                    echo 'Building image for deployment..'
                    def dockerImage = docker.build("${docker_image_name}", docker_build_command)

                    echo 'Pushing image to dockerhub..'
                    docker.withRegistry(docker_registry, docker_credentials_id ) {
                        dockerImage.push(version)
                    }
                }
            }
        }
        stage('Update value in helm-chart') {
            steps {
                script {
                    echo "Updating Helm chart configuration"
                    ls


                }
            }
        }
        
        // stage('Deploy') {
        //     agent {
        //         kubernetes {
        //             containerTemplate {
        //                 name 'helm' // Name of the container to be used for helm upgrade
        //                 image 'quandvrobusto/jenkins:lts-jdk17' // The image containing helm
        //                 alwaysPullImage true // Always pull image in case of using the same tag
        //             }
        //         }
        //     }
        //     steps {
        //         script {
        //             container('helm') {
        //                 sh("./scripts/model-serving.sh")
        //             }
        //         }
        //     }
        // }
    }
}