apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: 
    app: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 0.1
              memory: 500Mi
          ports:
          - containerPort: 8000
          env:
            - name: OLTP_ENDPOINT
              value: "grpc://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OLTP_INSECURE
              value: "true"
            - name: SERVICE_NAME
              value: "prompt_guardrail"
          volumeMounts:
          - name: foo
            mountPath: "/etc/foo"
            readOnly: true
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"
          - name: mypvc
            mountPath: "/etc/mypvc"
      volumes:
      - name: foo
        configMap:
          name: game-demo
          items:
          - key: game.properties
            path: mounted_game_properties
      - name: secret-volume
        secret:
          secretName: dotfile-secret
      - name: mypvc
        persistentVolumeClaim:
          claimName: myclaim3

          