FROM python:3.10.18-bullseye

LABEL AUTHOR=MINHHUY

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn","app:app","--workers", "4", "--host", "0.0.0.0", "--port", "8000"]